### ISSUE TITLE
Project Todo List

### ISSUE THREAD

**Issue by KenjiChao** [KenjiChao/android-boilerplate#1]
High Priority
- [x] Use retrolambda for java 8 lambda expressions
- [ ] Implement RxBus to replace Otto
- [ ] Review Dagger 2 and Refactor
- [ ] Review MVP architecture and Refactor
- [ ] Change the sample app to retrieve public github repositories (https://api.github.com/repositories)

If Time Permits
- [ ] Consider using Realm or other ORM library to replace SqlBrite
- [ ] Use leakcanary to detect memory leak
- [ ] List suggested readings to pick up the architecture quickly
